# Generated by Django 3.2.20 on 2023-07-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='advisor', serialize=False, to='user.user')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.TextField(default='')),
                ('years_of_experience', models.IntegerField(default=0)),
                ('current_role', models.CharField(blank=True, max_length=255, null=True)),
                ('current_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_per_hour', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='account_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_advisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
