# Generated by Django 3.2.20 on 2023-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230728_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='advisor',
            name='availability',
            field=models.ManyToManyField(to='user.Availability'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='expertise',
            field=models.ManyToManyField(to='user.Expertise'),
        ),
    ]
